### ISSUE TITLE
[Help] Getting Started

### ISSUE THREAD

**Issue by 0xkelvin** [security-union/leptos-webtransport-template#10]
hello @darioalessandro 

i was followed ReadMe to run this project. 
i ended up with the wasm version miss-matching, i am not sure, i am not familiar with wasm. 

![image](https://github.com/user-attachments/assets/6754b4bb-2608-4600-9dcd-2728643ca37d)

```
cargo update -p wasm-bindgen --precise 0.2.93
```

i also try to update wasm-bindgen dependency but also doesnt work.

Appreciate for your advice thanks

**Comment by 0xkelvin** [comment]
<img width="621" alt="image" src="https://github.com/user-attachments/assets/f4b4511c-1a64-480e-8bca-5edd4601fe11">


i checked, i have on my machine 0.2.89 wasm-bindgen version

but still running into the same error

**Comment by darioalessandro** [comment]
Hey brother, the issue is that there are compat bugs with the latest rust, let me update the readme with a combination of dependencies that actually work, cheers

**Comment by darioalessandro** [comment]
it is done, https://github.com/security-union/webtransport.rs/pull/11 

can you take a look at the PR and try testing  please?

**Comment by darioalessandro** [comment]
hey @0xkelvin please give it a go with the latest main branch. I automated toolchain selection so that we do not have to install "the right version" by hand.

**Comment by 0xkelvin** [comment]
thanks @darioalessandro for your support. 
i think the environment is settle (rust nightly, wasm 0.2.93..) , but i still dont know why i running into the same problem

<img width="790" alt="image" src="https://github.com/user-attachments/assets/c57a3837-60db-4506-9bc2-197639691367">

trying to investigate, quite interesting

**Comment by darioalessandro** [comment]
```
darioalessandro@MacBook-Pro-di-Dario webtransport.rs % wasm-bindgen -V
wasm-bindgen 0.2.93
```

````
darioalessandro@MacBook-Pro-di-Dario webtransport.rs % cargo leptos --version      
cargo-leptos 0.2.20
```

**Comment by 0xkelvin** [comment]
ah ok, then should update the Readme again too: 
```
1. `cargo install --locked cargo-leptos  --version 0.1.11`
```

should be 0.2.20

**Comment by 0xkelvin** [comment]
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/f72f898c-ea91-4a81-875c-337de0f61841">
it works, after all, 

thanks

**Comment by darioalessandro** [comment]
nice!! lets do this!! I am working to host it again, ran into some weird k8s certs issues.
